import '../models/user_role.dart';
import '../supabase/supabase_bootstrap.dart';

/// An invitation that lets one signup land as staff, delivery or owner
/// instead of customer.
class StaffInvite {
  const StaffInvite({
    required this.id,
    required this.email,
    required this.role,
    required this.inviteCode,
    required this.expiresAt,
    this.usedAt,
    required this.createdAt,
  });

  final String id;
  final String email;
  final UserRole role;
  final String inviteCode;
  final DateTime expiresAt;
  final DateTime? usedAt;
  final DateTime createdAt;

  bool get isUsed => usedAt != null;
  bool get isExpired => !isUsed && DateTime.now().isAfter(expiresAt);
  bool get isUsable => !isUsed && !isExpired;

  String get statusLabel {
    if (isUsed) return 'Used';
    if (isExpired) return 'Expired';
    return 'Waiting to be used';
  }

  factory StaffInvite.fromJson(Map<String, dynamic> json) => StaffInvite(
        id: json['id'] as String,
        email: json['email'] as String,
        role: UserRole.fromJson(json['role'] as String),
        inviteCode: json['invite_code'] as String,
        expiresAt: DateTime.parse(json['expires_at'] as String),
        usedAt: json['used_at'] == null
            ? null
            : DateTime.parse(json['used_at'] as String),
        createdAt: DateTime.parse(json['created_at'] as String),
      );
}

/// Somebody who already has an account with a staff-side role.
class TeamMember {
  const TeamMember({
    required this.id,
    required this.role,
    this.fullName,
    this.phone,
  });

  final String id;
  final UserRole role;
  final String? fullName;
  final String? phone;

  String get displayName =>
      (fullName?.trim().isNotEmpty ?? false) ? fullName! : 'Unnamed account';
}

/// Issuing and revoking staff invites. Owner-only, enforced by RLS: the
/// `staff_invites` policy is `is_owner()`, so a staff member calling any
/// of this simply sees nothing and writes nothing.
///
/// Accounts are never created directly here. The owner issues a code,
/// the person signs up with it themselves, and a database trigger
/// promotes their profile — so a password is only ever known by the
/// person it belongs to.
class StaffInviteRepository {
  Future<List<StaffInvite>> getInvites() async {
    final rows = await supabase
        .from('staff_invites')
        .select()
        .order('created_at', ascending: false)
        .limit(200);
    return rows.map(StaffInvite.fromJson).toList();
  }

  /// The code itself is generated by the database, so it is never
  /// guessable from anything the client knows.
  Future<StaffInvite> createInvite({
    required String email,
    required UserRole role,
    Duration validFor = const Duration(days: 7),
  }) async {
    final row = await supabase
        .from('staff_invites')
        .insert({
          'email': email.trim().toLowerCase(),
          'role': role.toJson(),
          // .toUtc() matters: a bare local timestamp is read as UTC by
          // Postgres, which in IST would quietly cut 5½ hours off the
          // invite's life.
          'expires_at': DateTime.now().toUtc().add(validFor).toIso8601String(),
          'created_by': supabase.auth.currentUser?.id,
        })
        .select()
        .single();
    return StaffInvite.fromJson(row);
  }

  /// Revoking is a delete: an unused invite that no longer exists cannot
  /// be redeemed. Already-used invites are kept as a record of who was
  /// let in and when.
  Future<void> revokeInvite(String id) async {
    await supabase.from('staff_invites').delete().eq('id', id);
  }

  /// Everyone who already holds a staff-side role.
  Future<List<TeamMember>> getTeam() async {
    final rows = await supabase
        .from('profiles')
        .select('id, role, full_name, phone')
        .inFilter('role', ['staff', 'owner', 'delivery'])
        .limit(200);
    return rows
        .map((row) => TeamMember(
              id: row['id'] as String,
              role: UserRole.fromJson(row['role'] as String),
              fullName: row['full_name'] as String?,
              phone: row['phone'] as String?,
            ))
        .toList();
  }
}
