-- Inventory audit log. products.stock_quantity is never updated
-- directly -- every change (restock, sale, cancellation, correction,
-- wastage) is recorded here, and a trigger applies it to the product's
-- cached total. This keeps a full history of why stock moved.

create type public.inventory_adjustment_reason as enum (
  'restock',
  'sale',
  'cancellation',
  'correction',
  'wastage'
);

create table public.inventory_adjustments (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  change_quantity integer not null check (change_quantity <> 0),
  reason public.inventory_adjustment_reason not null,
  reference_order_id uuid references public.orders (id) on delete set null,
  note text,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

comment on table public.inventory_adjustments is 'Append-only log; sale/cancellation rows are normally system-generated by order triggers, the rest are manual staff entries.';

create index inventory_adjustments_product_id_idx on public.inventory_adjustments (product_id);

create or replace function public.apply_inventory_adjustment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.products
  set stock_quantity = stock_quantity + new.change_quantity
  where id = new.product_id;
  return new;
end;
$$;

create trigger inventory_adjustments_apply
  after insert on public.inventory_adjustments
  for each row execute function public.apply_inventory_adjustment();

alter table public.inventory_adjustments enable row level security;

create policy "Staff and owner can view inventory adjustments"
  on public.inventory_adjustments for select
  to authenticated
  using (public.is_staff_or_owner());

create policy "Staff and owner can record inventory adjustments"
  on public.inventory_adjustments for insert
  to authenticated
  with check (public.is_staff_or_owner());
